"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var ClasePersona_1 = require("./ClasePersona");
var ClaseDireccion_1 = require("./ClaseDireccion");
var ClaseMail_1 = require("./ClaseMail");
var ClaseTelefono_1 = require("./ClaseTelefono");
var primeraResidenciaRocio = new ClaseDireccion_1.Direccion("Outid de Arriba", 15, 2, "D", 43519, "El Perelló", "Tarragona");
var segundaResidenciaRocio = new ClaseDireccion_1.Direccion("Paseo del Atlántico", 94, 6, "C", 18120, "Alhama De Granada", "Granada");
var mailRocio = new ClaseMail_1.Mail("personal", "Rocioemail@gmail.com");
var telefonoFijoRocio = new ClaseTelefono_1.Telefono("fijo", 972325254);
var telefonoMovilRocio = new ClaseTelefono_1.Telefono("movil", 696232325);
var datosRocio = new ClasePersona_1.Persona('Rocio', 'Corral Segundo', 26, '49567897S', new Date(1997, 4, 13), 'Amarillo', 'mujer', [primeraResidenciaRocio, segundaResidenciaRocio], [mailRocio], [telefonoFijoRocio, telefonoMovilRocio], "Estudia en la población de la segunda residencia");
var primeraResidenciaAdrian = new ClaseDireccion_1.Direccion("Travesía Nerea", 26, 3, "B", 11945, "La Lomeli", "Segovia");
var segundaResidenciaAdrian = new ClaseDireccion_1.Direccion("Praza Garrido", 41, 8, "A", 74313, "Lebrón de San Pedro", "Sevilla");
var mailPersonalAdrian = new ClaseMail_1.Mail("personal", "AdrianUrbina@hotmail.com");
var mailTrabajoAdrian = new ClaseMail_1.Mail("personal", "AdriantrabajoMK@outlook.es");
var telefonoFijoAdrian = new ClaseTelefono_1.Telefono("fijo", 968397854);
var telefonoMovilAdrianPersonal = new ClaseTelefono_1.Telefono("movil", 663555709);
var telefonoMovilAdrianTrabajo = new ClaseTelefono_1.Telefono("movil", 645635800);
var datosAdrian = new ClasePersona_1.Persona('Adrian', 'Urbina Delgado', 34, '55082914F', new Date(1985, 5, 27), 'Rojo', 'hombre', [primeraResidenciaAdrian, segundaResidenciaAdrian], [mailPersonalAdrian, mailTrabajoAdrian], [telefonoFijoAdrian, telefonoMovilAdrianPersonal, telefonoMovilAdrianTrabajo], "Sus hermanos viven en la segunda residencia");
var primeraResidenciaLisa = new ClaseDireccion_1.Direccion("Plaza Marco", 30, 1, "A", 95088, "San Martí de la Sierra", "Castellón");
var segundaResidenciaLisa = new ClaseDireccion_1.Direccion("Carrer Rodarte", 809, 3, "C", 63520, "Aljaraque", "Huelva");
var mailPersonalLisa = new ClaseMail_1.Mail("personal", "LisaTorres97@gmail.com");
var mailTrabajoLisa = new ClaseMail_1.Mail("trabajo", "lisaMKD@bestproyect.es");
var telefonoFijoLisa = new ClaseTelefono_1.Telefono("fijo", 9538573213);
var telefonoMovilLisa = new ClaseTelefono_1.Telefono("movil", 6735895521);
var datosLisa = new ClasePersona_1.Persona('Lisa', 'Torres Crespo', 25, '46753784M', new Date(1995, 7, 29), 'azul cielo', 'mujer', [primeraResidenciaLisa, segundaResidenciaLisa], [mailPersonalLisa, mailTrabajoLisa], [telefonoFijoLisa, telefonoMovilLisa], "La segunda residencia es para su madre");
console.log("Contactos antes del cambio:");
console.log(datosRocio);
console.log(datosAdrian);
console.log(datosLisa);
var agenda = new Array(datosRocio, datosAdrian, datosLisa);
var dniABuscar = "49567897S";
var personaAEditar = agenda.find(function (persona) { return persona.dni === dniABuscar; });
var nuevaDireccion = new ClaseDireccion_1.Direccion("Plaza Cruz", 10, 7, "B", 94616, "La Garza", "Jaén");
var nuevoMail = new ClaseMail_1.Mail("trabajo", "marketingdigitalayuda@outlook.com");
var nuevoTelefono = new ClaseTelefono_1.Telefono("fijo", 995664739);
personaAEditar.agregarNuevaDireccion(nuevaDireccion);
personaAEditar.agregarNuevoMail(nuevoMail);
personaAEditar.agregarNuevoTelefono(nuevoTelefono);
console.log("Contactos después del cambio:");
console.log(datosRocio);
console.log(datosAdrian);
console.log(datosLisa);
